### ISSUE TITLE
New Post Not Appearing After Creation

### ISSUE THREAD

**Issue by ilyaux** [StarKhan6368/threaddit#4]
Description

Hello, StarKhan6368.

I am currently experiencing an issue with the Threaddit project. When I create a new post, it does not appear on the frontend. After thoroughly debugging, I noticed that the post is not being saved in the database, despite the request seeming to succeed. Additionally, the page reloads upon post creation, causing the state to reset, which might be masking any frontend updates.
Steps to Reproduce

    Clone the Threaddit repository.
    Set up the backend and frontend environments as per the instructions.
    Log in as a registered user.
    Click on the "+ / Create Post" button.
    Fill in the post details and submit.

Expected Behavior

The new post should appear immediately in the subthread after creation.

Actual Behavior

The post does not appear on the frontend, and upon inspecting the database, the post is not saved.

Debugging Steps Taken

    Checked Backend Logs: The logs show that the POST request is being received and processed without any errors.
    Database Inspection: Verified that no new entries are created in the posts table.
    Frontend Behavior: Observed that the page reloads upon post submission, which might be related to the issue.

**Comment by StarKhan6368** [comment]
Hello @ilyaux , Thanks for pointing that out and sorry for the delay in fixing it. It should be working now. It seems there were some changes in React Query. I wonder what else might be affected since it uses React Query extensively.
