### ISSUE TITLE
Issue with the find community search when creating a post

### ISSUE THREAD

**Issue by thisisMoe** [StarKhan6368/threaddit#6]
To reproduce:

1. Login
2. Click on the + button in the bottom right corner (Desktop)
3. Type one forward slash / in the find community search bar and it should crash :/

**Comment by StarKhan6368** [comment]
Hello @thisisMoe , thank you for bringing this to attention. The issue should now be fixed.
No idea what i was thinking when making that endpoint, also added validation on thread name.
